## Compose para Postgres
services:
  postgres:
    image: postgres:15.3-alpine
    container_name: sgi-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  redis:
   image: redis:7.0.11-alpine
   container_name: sgi-redis
   restart: always
   ports:
     - 6379:6379
   command: redis-server --save 60 1 --loglevel warning
   volumes:
     - ./data/redis:/data