## Compose para Postgres
services:
  sgi-postgres:
    image: postgres:15.3-alpine
    container_name: sgi-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sgi
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
